final List<dynamic> cowBreeds = [
  {"value": "amritmahal", "title": "Amritmahal"},
  {"value": "bachaur", "title": "Bachaur"},
  {"value": "badri", "title": "Badri"},
  {"value": "bargur", "title": "Bargur"},
  {"value": "belahi", "title": "Belahi"},
  {"value": "binjharpuri", "title": "Binjharpuri"},
  {"value": "dagri", "title": "Dagri"},
  {"value": "dangi", "title": "Dangi"},
  {"value": "deoni", "title": "Deoni"},
  {"value": "gir", "title": "Gir"},
  {"value": "hariana", "title": "Hariana"},
  {"value": "kankrej", "title": "Kankrej"},
  {"value": "khariar", "title": "Khariar"},
  {"value": "ladakhi", "title": "Ladakhi"},
  {"value": "malnadGidda", "title": "Malnad Gidda"},
  {"value": "malvi", "title": "Malvi"},
  {"value": "mewati", "title": "Mewati"},
  {"value": "malvi", "title": "Malvi"},
  {"value": "nagori", "title": "Nagori"},
  {"value": "purnea", "title": "Purnea"},
  {"value": "redSindhi", "title": "Red Sindhi"},
  {"value": "sahiwal", "title": "Sahiwal"},
  {"value": "siri", "title": "Siri"},
];

final List<dynamic> goatBreeds = [
  {"value": "attappadyBlack", "title": "Attappady Black"},
  {"value": "barbari", "title": "Barbari"},
  {"value": "beetal", "title": "Beetal"},
  {"value": "berari", "title": "Berari"},
  {"value": "boar", "title": "Boar"},
  {"value": "blackBengal", "title": "Black Bengal"},
  {"value": "changthangi", "title": "Changthangi"},
  {"value": "chegu", "title": "Chegu"},
  {"value": "changraOrChangthangi", "title": "Changra / Changthangi"},
  {"value": "gaddi", "title": "Gaddi"},
  {"value": "Ganjam", "title": "Ganjam"},
  {"value": "gohilwadi", "title": "Gohilwadi"},
  {"value": "jakhrana", "title": "Jakhrana"},
  {"value": "jamunapari", "title": "Jamunapari"},
  {"value": "kanniAadu", "title": "Kanni Aadu"},
  {"value": "kodiAadu", "title": "Kodi Aadu"},
  {"value": "kutchiOrKathiawari", "title": "Kutchi / Kathiawari"},
  {"value": "konkanKanyal", "title": "Konkan Kanyal"},
  {"value": "malabariOrTellicherry", "title": "Malabari / Tellicherry"},
  {"value": "marwari", "title": "Marwari"},
  {"value": "mehsana", "title": "Mehsana"},
  {"value": "osmanabadi", "title": "Osmanabadi"},
  {"value": "sangamneri", "title": "Sangamneri"},
  {"value": "sirohi", "title": "Sirohi"},
  {"value": "surti", "title": "Surti"},
  {"value": "zalawadi", "title": "Zalawadi"}
];
